### ISSUE TITLE
go: github.com/jwplayer/jwplatform-go@v0.2.0: parsing go.mod: 	module declares its path as: github.com/jwplayer/jwplayer-go/v0.1.0 	        but was required as: github.com/jwplayer/jwplatform-go

### ISSUE THREAD

**Issue by lombokcyberlc** [jwplayer/jwplatform-go#10]
always show this error messages when i run go get -u github.com/jwplayer/jwplatform-go
go: github.com/jwplayer/jwplatform-go@v0.2.0: parsing go.mod:
	module declares its path as: github.com/jwplayer/jwplayer-go/v0.1.0
	        but was required as: github.com/jwplayer/jwplatform-go

**Comment by ksindi** [comment]
Thanks @lombokcyberlc. Will look into it.

**Comment by ksindi** [comment]
@lombokcyberlc I haven't come across this issue. Are you just running
```
go get -u github.com/jwplayer/jwplatform-go
```

Perhaps remove jwplatform-go from your gopath and do a fresh `get`?

**Comment by ksindi** [comment]
@lombokcyberlc can you see if you can reproduce it in docker?

Dockerfile:
```
FROM golang:latest

ENV GOBIN /go/bin

RUN go get github.com/jwplayer/jwplatform-go
```

Then run:
```
docker build -t test .

docker run -it test bash
```

**Comment by lombokcyberlc** [comment]
an error occurs when I use go mod.

**Comment by ksindi** [comment]
Thanks @lombokcyberlc. I can't reproduce; `go mod` works fine for me. Can you please share an example inside a Dockerfile?

**Comment by lombokcyberlc** [comment]
i don't use docker

**Comment by ksindi** [comment]
@lombokcyberlc I found the issue. Let me fix this weekend.

**Comment by lombokcyberlc** [comment]
thanks, keep spirit brother.

**Comment by ksindi** [comment]
@lombokcyberlc try v0.3.0

**Comment by lombokcyberlc** [comment]
i will try soon

Pada tanggal Sab, 16 Mei 2020 23:49, Kamil Sindi <notifications@github.com>
menulis:
