### ISSUE TITLE
Failed to install, error parsing go.mod

### ISSUE THREAD

**Issue by miun173** [jwplayer/jwplatform-go#9]
im trying to use install this into my project, but i got error
```
go get -u github.com/jwplayer/jwplatform-go       
go: github.com/jwplayer/jwplatform-go@v0.2.0: parsing go.mod:
        module declares its path as: github.com/jwplayer/jwplayer-go/v0.1.0
                but was required as: github.com/jwplayer/jwplatform-go
```

For now, to resolve the issue i need to clone this repo and add replace in my `go.mod` project
```
go 1.13

require (
    ...
    github.com/jwplayer/jwplatform-go v0.2.0
    ...
)

replace github.com/jwplayer/jwplatform-go => /path/to/local/jwplatform-go
```

**Comment by ksindi** [comment]
Thanks @miun173! Will fix shortly.

**Comment by ksindi** [comment]
@miun173 updated. Can you please confirm it works for you now?

**Comment by miun173** [comment]
@ksindi sorry still got the same problem, i believe the problem is the module path, as the error says
```
 module declares its path as: github.com/jwplayer/jwplayer-go/v0.1.0
                but was required as: github.com/jwplayer/jwplatform-go
``` 

in the `go.mod` it should be omit the version for v1 and below
```
module github.com/jwplayer/jwplayer-go
```

**Comment by ksindi** [comment]
Thanks again @miun173. Should work now. Mind verifying before I close out?

**Comment by miun173** [comment]
@ksindi i looked to this commit https://github.com/jwplayer/jwplatform-go/commit/c1f5f0321b7b32a68a66d5c32896275a8c08de52 , but it's not correct. The correct way to declare go module sould **match with the repo url**. This repo url is  `github.com/jwplayer/jwplatform-go` so the go module path should be `github.com/jwplayer/jwplatform-go`. Or you can change the repo url to match the current go module. 
cmiiw

**Comment by ksindi** [comment]
Thanks @miun173. Silly oversight. I overwrote v0.2.0. You can try now.

**Comment by miun173** [comment]
@ksindi thank you, it works now :+1:

**Comment by ksindi** [comment]
Perfect. Thanks again for the help.
